### ISSUE TITLE
When will v0.4.0 be released?

### ISSUE THREAD

**Issue by abiezev** [gonuit/gauge_indicator#3]
Great widget! Looking to use the `cornerRadius` in segment. When will v0.4.0 be released?

**Comment by gonuit** [comment]
Hi, @abiezev!
It's been a long journey 😅, but 0.4.0 finally made it to pub.dev 💪🏻. 

The package [version 0.4.1 is now available on the pub.dev](https://pub.dev/packages/gauge_indicator/versions/0.4.1).
